# Version 1.0.0.50
# By YXStudio 2023~2025.
# Feb.22nd,2025


from tkinter import *


root = Tk()

def main():
    root.iconbitmap('_internal/icon/icon.ico')
    root.title('MINECRAFT 1.0.0.50 - About')
    

    label1 = Label(root,text='MINECRAFT',font=('minecrafter',35),foreground='#262626')
    label2 = Label(root,text='PYTHON EDITION',font=('minecraft ae pixel',10),foreground='#8F8F8F')
    
    padding1 = Label(root,text='',font=('微软雅黑',16))
    label3 = Label(root,text='Versions',font=('minecrafter',21))
    label23a = Label(root,text='FEB.22ND,2025',font=('minecraft',10),foreground='black')
    label22a = Label(root,text='Jan.1st,2025' ,font=('minecraft',10),foreground='grey')
    label21a = Label(root,text='Nov.24th,2024',font=('minecraft',10),foreground='grey')
    label20a = Label(root,text='Oct.8th,2024' ,font=('minecraft',10),foreground='grey')
    label19a = Label(root,text='Oct.7th,2024' ,font=('minecraft',10),foreground='grey')
    label18a = Label(root,text='Oct.1st,2024' ,font=('minecraft',10),foreground='grey')
    label17a = Label(root,text='Aug.31st,2024',font=('minecraft',10),foreground='grey')
    label16a = Label(root,text='Aug.20th,2024',font=('minecraft',10),foreground='grey')
    label15a = Label(root,text='Aug.18th,2024',font=('minecraft',10),foreground='grey')
    label14a = Label(root,text='Aug.10th,2024',font=('minecraft',10),foreground='grey')
    label13a = Label(root,text='Aug.7th,2024' ,font=('minecraft',10),foreground='grey')
    label12a = Label(root,text='Aug.6th,2024' ,font=('minecraft',10),foreground='grey')
    label11a = Label(root,text='Aug.5th,2024' ,font=('minecraft',10),foreground='grey')
    label10a = Label(root,text='Jul.16th,2024',font=('minecraft',10),foreground='grey')
    label9a  = Label(root,text='Jul.13th,2024',font=('minecraft',10),foreground='grey')
    label8a  = Label(root,text='Jul.12th,2024',font=('minecraft',10),foreground='grey')
    label7a  = Label(root,text='Feb.13th,2024',font=('minecraft',10),foreground='grey')
    label6a  = Label(root,text='Feb.9th,2024' ,font=('minecraft',10),foreground='grey')
    label5a  = Label(root,text='Jun.1st,2024' ,font=('minecraft',10),foreground='grey')
    label4a  = Label(root,text='Jan.19th,2023',font=('minecraft',10),foreground='grey')

    label23b = Label(root,text='V1.0.0.50     ',font=('minecraft',10),foreground='black')
    label22b = Label(root,text='v5.1.0.39-beta',font=('minecraft',10),foreground='grey')
    label21b = Label(root,text='v5.0.0.36-beta',font=('minecraft',10),foreground='grey')
    label20b = Label(root,text='v4.1.0.34-beta',font=('minecraft',10),foreground='grey')
    label19b = Label(root,text='v4.0.0.30-beta',font=('minecraft',10),foreground='grey')
    label18b = Label(root,text='v3.2.0.26-beta',font=('minecraft',10),foreground='grey')
    label17b = Label(root,text='v3.1.1.24-beta',font=('minecraft',10),foreground='grey')
    label16b = Label(root,text='v3.1.0.21-beta',font=('minecraft',10),foreground='grey')
    label15b = Label(root,text='v3.0.0.18-beta',font=('minecraft',10),foreground='grey')
    label14b = Label(root,text='v2.3.0.16-beta',font=('minecraft',10),foreground='grey')
    label13b = Label(root,text='v2.2.0.12-beta',font=('minecraft',10),foreground='grey')
    label12b = Label(root,text='v2.1.0.8-beta' ,font=('minecraft',10),foreground='grey')
    label11b = Label(root,text='v2.0.0.5-beta' ,font=('minecraft',10),foreground='grey')
    label10b = Label(root,text='v1.2.0.4-beta' ,font=('minecraft',10),foreground='grey')
    label9b  = Label(root,text='v1.1.1.3-beta' ,font=('minecraft',10),foreground='grey')
    label8b  = Label(root,text='v1.1.0.2-beta' ,font=('minecraft',10),foreground='grey')
    label7b  = Label(root,text='v1.0.0.0-beta' ,font=('minecraft',10),foreground='grey')
    label6b  = Label(root,text='v0.1.1.0-alpha',font=('minecraft',10),foreground='grey')
    label5b  = Label(root,text='v0.1.0.0-alpha',font=('minecraft',10),foreground='grey')
    label4b  = Label(root,text='v0.0.0.0-alpha',font=('minecraft',10),foreground='grey')
    
    label22c = Label(root,text='====================',font=('minecraft',10),foreground='black')
    label22c = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label21c = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label20c = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label19c = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label18c = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label17c = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label16c = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label15c = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label14c = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label13c = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label12c = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label11c = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label10c = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label9c  = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label8c  = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label7c  = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label6c  = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label5c  = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    label4c  = Label(root,text='--------------------',font=('minecraft',10),foreground='grey')
    
    padding2 = Label(root,text='',font=('微软雅黑',11))
    label0a = Label(root,text='ABOUT',font=('minecrafter',22))
    label0b = Label(root,text='Minecraft Python Edition is a game like Minecraft but written in Python .\nMinecraft Python Edition (MPE) by 2023~2025 YXStudio , is not to Minecraft Java Edition , Minecraft Bedrock Edition , Mojang Studio , 网易 , and Microsoft .\nhttps://github.com/YX-Studio/Minecraft_Python_Edition for more information .',font=('minecraft ae pixel',8),foreground='grey')


    label1.grid(row=0,columnspan=3)
    label2  .grid(row=1,columnspan=3)
    padding1.grid(row=2,columnspan=3)
    label3  .grid(row=3,columnspan=3)

    line = 23
    label23a.grid(row=line-19,column=0)
    label23a.grid(row=line-19,column=1)
    label23a.grid(row=line-19,column=2)
    label22a.grid(row=line-18,column=0)
    label22c.grid(row=line-18,column=1)
    label22b.grid(row=line-18,column=2)
    label21a.grid(row=line-17,column=0)
    label21c.grid(row=line-17,column=1)
    label21b.grid(row=line-17,column=2)
    label20a.grid(row=line-16,column=0)
    label20c.grid(row=line-16,column=1)
    label20b.grid(row=line-16,column=2)
    label19a.grid(row=line-15,column=0)
    label19c.grid(row=line-15,column=1)
    label19b.grid(row=line-15,column=2)
    label18a.grid(row=line-14,column=0)
    label18c.grid(row=line-14,column=1)
    label18b.grid(row=line-14,column=2)
    label17a.grid(row=line-13,column=0)
    label17c.grid(row=line-13,column=1)
    label17b.grid(row=line-13,column=2)
    label16a.grid(row=line-12,column=0)
    label16c.grid(row=line-12,column=1)
    label16b.grid(row=line-12,column=2)
    label15a.grid(row=line-11,column=0)
    label15c.grid(row=line-11,column=1)
    label15b.grid(row=line-11,column=2)
    label14a.grid(row=line-10,column=0)
    label14c.grid(row=line-10,column=1)
    label14b.grid(row=line-10,column=2)
    label13a.grid(row=line-9,column=0)
    label13c.grid(row=line-9,column=1)
    label13b.grid(row=line-9,column=2)
    label12a.grid(row=line-8,column=0)
    label12c.grid(row=line-8,column=1)
    label12b.grid(row=line-8,column=2)
    label11a.grid(row=line-7,column=0)
    label11c.grid(row=line-7,column=1)
    label11b.grid(row=line-7,column=2)
    label10a.grid(row=line-6,column=0)
    label10c.grid(row=line-6,column=1)
    label10b.grid(row=line-6,column=2)
    label9a.grid(row=line-5,column=0)
    label9c.grid(row=line-5,column=1)
    label9b.grid(row=line-5,column=2)
    label8a.grid(row=line-4,column=0)
    label8c.grid(row=line-4,column=1)
    label8b.grid(row=line-4,column=2)
    label7a.grid(row=line-3,column=0)
    label7c.grid(row=line-3,column=1)
    label7b.grid(row=line-3,column=2)
    label6a.grid(row=line-2,column=0)
    label6c.grid(row=line-2,column=1)
    label6b.grid(row=line-2,column=2)
    label5a.grid(row=line-1,column=0)
    label5c.grid(row=line-1,column=1)
    label5b.grid(row=line-1,column=2)
    label4a.grid(row=line,column=0)
    label4c.grid(row=line,column=1)
    label4b.grid(row=line,column=2)

    padding2.grid(row=line+1,columnspan=3)
    label0a.grid(row=line+2,columnspan=3)
    label0b.grid(row=line+3,columnspan=3)

    root.mainloop()
    
main()